[package]
name = "tigon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = "0.11.2"
indicatif = "0.17.3"
intmap = "2.0.0"
rand = "0.8.5"
shakmaty = "0.25.0"
